name: Check-Actor-Permission-To-Run-Workflow
run-name: Check-Actor-Permission-To-Run-Workflow
on:
  workflow_call:
  workflow_dispatch: 
jobs:
 Check-Actor-Permission-To-Run-Workflow:
  name: Check-Actor-Permission-To-Run-Workflow
  runs-on: ubuntu-latest
  env:
    ALLOWED_ACTORSINPUT: '["martin2176", "item2", "item3"]'
  steps:
  - name: Exit-If-Actor-Not-Allowed
    continue-on-error: false
    if: ${{ !contains(fromJSON('["octocat", "mona"]'), github.actor) }}
    run: |
     echo "::error title=Validation Failed::The variable value is invalid."
     exit 1

