name: reusableworkflow
run-name: reusableworkflow
on:
  workflow_call:
permissions:
  id-token: write
  contents: read
jobs:
 reusableworkflow:
  runs-on: ubuntu-latest
  env:
    INPUT: ${{ toJSON(inputs) }}
    EVENT_INPUT: ${{ toJSON(github.event.inputs) }}
    EVENT: ${{ toJSON(github.event) }}
    GITHUB: ${{ toJSON(github) }}
  steps:
  - name: Debug
    run: |
     echo "actor=${{github.actor}}"
     echo "actorid=${{github.actor_id}}"
     echo "event.inputs: $EVENT_INPUT"
     echo "inputs: $INPUT"
     echo "event: $EVENT"
     echo "github: $GITHUB"
