name: Manual-Trigger-To-Create-APIM-Repo
run-name: Manual-Trigger-To-Create-APIM-Repo
#martin francis kallukalam
on:
  workflow_dispatch:
    inputs:
      REPO_NAME:
        description: 'Enter name of APIM repo in the format lowercase apim-<apiname>'     
        required: true
        type: string
permissions:
  contents: write
  id-token: write
env:
  TEMPLATE_REPO: "martin2176/apim-secrets"
  REPO: "martin2176/${{ inputs.REPO_NAME }}"
  APIM_APPROVERS_TEAM_ID: 16495124
  RULESET_NAME: "Require-Pull-Request"
  
jobs:
  Create-and-Configure-AIM-Repo:
    name: Create-and-Configure-AIM-Repo
    runs-on: ubuntu-latest
    env:
     GH_TOKEN: ${{ secrets.MARTIN_PAT_TOKEN }}
    steps:
      - name: Create-Private-Repo-From-Template-Repo
        id: create-private-repo-from-template-repo
        shell: bash  
        run: |
          gh repo view "$REPO" > /dev/null 2>&1 || gh repo create "$REPO" --template "$TEMPLATE_REPO" --private
      - name: Delete-Ruleset-If-Exists
        id: delete-ruleset-if-exists
        shell: bash
        run: |
         RULESET_ID=$(gh api repos/${{ env.REPO }}/rulesets \
         --jq ".[] | select(.name == \"${{ env.RULESET_NAME }}\") | .id")
         if [ -n "$RULESET_ID" ]; then
         gh api --method DELETE repos/${{ env.REPO }}/rulesets/$RULESET_ID
         else
          echo "Ruleset not found.Nothing to delete.Continuing" 
         fi
      - name: Create-Branch-Protection-Ruleset
        id: create-branch-protection-rule-set
        shell: bash  
        run: |
          echo '{
           "name": "${{ env.RULESET_NAME }}",
           "target": "branch",
           "enforcement": "active",
           "conditions": {
            "ref_name": {
            "exclude": [],
            "include": [
            "refs/heads/main"
            ]
            }
            },
           "bypass_actors": [],
           "rules": [
           {
           "type": "deletion"
           },
           {
           "type": "non_fast_forward"
           },
           {
           "type": "pull_request",
           "parameters": {
           "required_approving_review_count": 1,
           "dismiss_stale_reviews_on_push": true,
           "required_reviewers": [ ],
           "require_code_owner_review": true,
           "require_last_push_approval": true,
           "required_review_thread_resolution": false,
           "allowed_merge_methods": [
           "merge",
           "squash"
           ]
           }
           }
           ]
           }' > data.json
          gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2026-03-10" /repos/$REPO/rulesets --input data.json
