name: Manual-Trigger-To-Create-APIM-Repo
run-name: Manual-Trigger-To-Create-APIM-Repo
#martin francis kallukalam
on:
  workflow_dispatch:
    inputs:
      REPO_NAME:
        description: 'Enter name of APIM repo in the format lowercase apim-<apiname>'     
        required: true
        type: string
permissions:
  contents: write
  id-token: write
env:
  TEMPLATE_REPO: "martin2176/apim-secrets"
jobs:
  Create-and-Configure-AIM-Repo:
    name: Create-and-Configure-AIM-Repo
    runs-on: ubuntu-latest
    env:
     GH_TOKEN: ${{ secrets.MARTIN_PAT_TOKEN }}
    steps:
      - name: Create-Private-Repo-From-Template-Repo
        id: create-private-repo-from-template-repo
        shell: bash  
        run: |
          gh repo create ${{ inputs.REPO_NAME }} --template "$TEMPLATE_REPO" --private
